name: CI-CD
on:
  push:
    branches:
      - aula-04

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.11.2
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Change directory
        run: cd projeto-teste
      - name: Install dependencies
        run: npm install
        working-directory: projeto-teste
      - name: Run build
        run: npm run build
        working-directory: projeto-teste
